name: Test & Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - master
        tags:
            - "*"
    pull_request:
        branches:
            - master

jobs:
    run:
        uses: Ionaru/Ionaru/.github/workflows/npm-main.yaml@main
        with:
            node-versions: '["20", "22", "24"]'
            deploy-jsr: true
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
